### ISSUE TITLE
Extended key usage normative language

### ISSUE THREAD

**Issue by PieterKas** [ietf-wg-wimse/draft-ietf-wimse-s2s-protocol#74]
Comparing the normative language for WIMSE certificates and X.509 SVIDs appears to suggest that extended key usage MUST include both server and client auth extended key usage, while for WIMSE, it is optional and you can have one or the other. Is there a specific reason why we want to be more lenient in the WIMSE draft than in the SPIFFE drafts?

**Comment by yaronf** [comment]
IMO what we have right now is reasonable: if you're a server, include server auth EKU; if you're a client, include client auth EKU; if you're both include both. Arguably it's more flexible than what they have in SPIFFE, because some services may in fact be server-only.

If in the future we go through consolidation of WIMSE and SPIFFE (which I'm supportive of), we could change the language to be more stringent.
